### ISSUE TITLE
SCRIPT ERROR: @esx_shops/server/main.lua:60: attempt to call a nil value (field 'canCarryItem')

### ISSUE THREAD

**Issue by KeinMiner** [esx-framework/esx_shops#87]
Hello i have a Problem with esx_shops when i start the Server it says nothing in f8 but in the Server console it is showing this SCRIPT ERROR: @esx_shops/server/main.lua:60: attempt to call a nil value (field 'canCarryItem') i have everything on the latest version

**Comment by tobipazos25** [comment]
I'm having the same issue, i cant solve it

**Comment by ThatGuyJacobee** [comment]
Same here.

**Comment by Riggins1** [comment]
Same

**Comment by ThatGuyJacobee** [comment]
Solution: Update your ESX to the latest version (don't use ESX 2). I've just re-installed everything fresh using the final edition of the first ESX and that fixed all of my issues. It's because the final update uses a inventory weight system, where as previously there was none hence it's causes issues.
Hope this helps :)
https://github.com/ESX-Org/es_extended/tree/v1-final
